### ISSUE TITLE
Add to MELPA

### ISSUE THREAD

**Issue by danielmatz** [ffevotte/slurm.el#2]
Have you considered adding this package to MELPA?

**Comment by Blade6570** [comment]
Hi @ffevotte, I am planning to add this to Melpa to increase its visibility. If you think otherwise then please let me know.

**Comment by ffevotte** [comment]
Sounds like a great idea to me! Do you need help with the process?

**Comment by Blade6570** [comment]
This will be my first time to add something to Melpa. I have created the recipe and will add the pull request today. If it does not work then I will ask you for help.

**Comment by Blade6570** [comment]
Now it is in Melpa :). I will update the README with additional information.

**Comment by ffevotte** [comment]
Thanks a lot @Blade6570 !
