### ISSUE TITLE
Inconsistent username and machine TRAMP

### ISSUE THREAD

**Issue by markgdawson** [ffevotte/slurm.el#5]
This package has a few issues for me over TRAMP for me.

It seems to globally persist the default-directory value of the buffer from which `M-x slurm` was first invoked. Causing issues with repeat calls to `M-x slurm`.

In particular the default-directory when `shell-command` is called inside `slurm--run-command` is always the default-directory from which `M-x slurm` was initially called. It causes issues for me when username is different on the local and remote machines, since the directory of first invocation is cached globally, but the user name related to that directory is not.

### Reproduction steps

* Wrong username issue:

    1. Start emacs
    2. run `M-x slurm` in a buffer visiting a TRAMP file/directory, e.g. /ssh:some-machine:~/
    3. delete this buffer
    4. run `M-x slurm` in a buffer visiting a local file/directory
    5. Observer the local username is being used for queue command on the remote machine

* Wrong machine issue:

    1. Start emacs
    2. run `M-x slurm` in a buffer visiting a local file/directory
    3. Realise your mistake
    4. Delete the slurm buffer
    5. Run `M-x slurm` in a buffer visiting a TRAMP file/directory
    6. slurm-mode.el caches the machine directory, and continues to look for squeue on the local machine.

I can think of three options that would be resolve the consistency issue:

* Don't remember the default-directory
Use the default-directory of the buffer from which `M-x slurm` was called. This means that every call to `M-x slurm` needs to be preceded with moving to a TRAMP directory on the remote machine. But eliminates the inconsistent user/machine bug. Maybe the easiest to implement?

* Cache default-directory as buffer local
Cache default-directory also, as a buffer local variable. Would this be possible to store in slurm--state, and pass a dir into calls to `slurm--run-command`? Is there a better way? Are there implementation limitations that mean that we need to remember the default-directory somewhere anyway?

* Keep values globally
Included mainly for completeness. Lots of ways of doing this, including the easy but controversial option of making slurm--state global. Having said that, it could open nice possibilities if done right. Like having an alist of known clusters in a .emacs file, and choosing them from a list on M-x slurm.

**Comment by M4rkD** [comment]
Reproduction steps:

Wrong username issue:
1) Start emacs
2) run `M-x slurm` in a buffer visiting a TRAMP file/directory, e.g. `/ssh:some-machine:~/`
3) delete this buffer
4) run `M-x slurm` in a buffer visiting a local file/directory
5) Observer the local username used for the remote machine


Wrong machine issue:
1) Start emacs
2) run `M-x slurm` in a buffer visiting a local file/directory
3) realise your mistake
4) delete the slurm buffer
5) run `M-x slurm` in a buffer visiting a TRAMP file/directory
5) Slurm caches the machine directory, and continues to look for squeue on the local machine.

**Comment by Blade6570** [comment]
The recent commits have fixed it. Please try it if you are still facing the same problem.
